<a href="https://colab.research.google.com/github/juanjacevedo/Intro-a-la-IA/blob/main/content/LAB%2001.01%20-%20PRACTICE%20SUBMISSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 01.01 - Practice submission

In [1]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()


replicating local resources


In [2]:
import inspect
from local.lib.rlxmoocapi import session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.01", varname="student");

logging in as juanj.acevedo@udea.edu.co... please wait
using course session ai4eng.v1::open
success!! you are logged in


### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     
_Sugerencia_: completa el código de la siguiente manera:

    def suma_matrices(a,b):
       ## --- TU CODIGO AQUI ---
       result = a + b
       return result

In [3]:

def suma_matrices(a,b):
    ## --- TU CODIGO AQUI ---
    result = a+b
    return result



comprueba manualmente tu código

In [4]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print (suma_matrices(a,b))

[[1 7]
 [1 9]
 [6 2]]
[[9 0]
 [1 7]
 [1 2]]
[[10  7]
 [ 2 16]
 [ 7  4]]


#### registra tu solución en línea

In [5]:
student.submit_task(globals(), task_id="task_01");

### Ejercicio 2: Realiza un cálculo 

En este ejercicio, al ejecutar la celda de más abajo, se generará una lista de número aleatorios.

Tendrás que calcular el valor promedio de la lista y asignarlo a la variable `avg` más abajo.

Puedes usar el método que quieras para realizar el cálculo (a mano, excel, python, etc.) lo que importa es el valor que obtengas.


In [10]:
import numpy as np
rlist = np.random.randint(100, size=10)
print(rlist)

[ 3 61 41 97  2 78 17 58 72  3]


#### tu solución

In [11]:
suma = 0
for i in rlist:
  suma += i 
avg = suma/len(rlist)

#### registra tu solución en línea

In [12]:
student.submit_task(globals(), task_id="task_02");